name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-python38:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_SECRETS }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_SECRETS }}
      GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE }}
      FINN_API_KEY: ${{ secrets.FINN_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run doctests for ragnews.py
        run: |
          python -m doctest -v ragnews.py

      - name: Run doctests for chatbot.py
        run: |
          python -m doctest -v chatbot.py

  test-python39:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_SECRETS }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_SECRETS }}
      GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE }}
      FINN_API_KEY: ${{ secrets.FINN_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run doctests for ragnews.py
        run: |
          python -m doctest -v ragnews.py

      - name: Run doctests for chatbot.py
        run: |
          python -m doctest -v chatbot.py
